---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
# stringData позволяет хранить значение в открытом виде в манифесте,
# Kubernetes сам закодирует его в base64 при создании Secret
stringData:
  DB: {{ .Values.env.DB | quote }}
